language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 0iNBUgBvGSnAVetkaNDxWt7cHs/MB3xslzIjegdtw2fZKrN7h8z87TDtXqYRZbHX1Y75Uzjo4DNGU9GEMODwyW5PSCOs3hdcGYjjdp0JHtFjAYl5XRqKXK6Xq6CTzEfcABBh1eSLOxFS7MCSX6RXCRXccS/xqDYZWuc1xqBerlTpM8tHEuuFE//FzEF91OTD3FmG0GJTwrmMbj+3s7p8Pl6jLs/hSvxbGll/1mqanNvkTn089hQ/qFcKVns1ZD4g+R32yMA4kNH7Ooy/92X5WGRWifiNhVxpGEFKbWNDbXYi9aewn/3Gu5zkuWxQOyy7QHF3d1cGavqf09c17js1s7bhSak785+LqW4GoXQYPmhLiw4qC2kRpOCAdwjBirCDzaW/80Jyuu3Tzj7vIdMleZnhi4KZ7Q8UtzmZ9SaVBFsmolWAcUehvfVSZ+IPml7nr4IEr/rPFM89g94OnZdZ1RG2gxy88fOzmiS8ffcUkweQIBpuAYz41tarAebA9/u+zJo0eNQC96XtzA/vdhz1cwJEW0lCW4kIH+DLcBxaBQSQjHe5vXfHibtbEIhYylkUamShIgVp5WtAyX3M7x/t3BvRiOxSWx0T27c9Jz16MDiK9sabJmh9X7uK/3aiKwnYbudYuj9xJV6oY00LmqUaYynkREsEUhjDku7R9OaUnEk=
  app: bloque-party
  run: rails db:migrate
  on:
    branch: main 